spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      enabled: false
      discovery:
        instanceId: ${spring.application.name}:${random.value}



application:
  value1: 'This is good INT'