spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      enabled: false
      discovery:
#        health-check-headers:
#          X-Config-Token: 6442e58b-d1ea-182e-cfa5-cf9cddef0722
        metadata:
            myfield: myvalue
            anotherfield: anothervalue
#        instanceId: ${spring.application.name}:${random.value}
        instanceId: ${spring.application.name}



application:
  value1: 'This is good INT'