spring:
  cloud:
    consul:
      host: localhost
      port: 8501
      config:
        enabled: true
      discovery:
        instanceId: ${spring.application.name}:${random.value}


application:
  value1: 'This is good INT'