server:
  port: 8098
management:
     security:
        enabled: false

spring:
  cloud:
    consul:
      enabled: true
      discovery:
        metadata:
          myfield: myvalue
          anotherfield: anothervalue
application:
  value1: 'This is good INT telemetry'



